spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/vacine
    username: postgres
    password: elonlima
  jpa:
    hibernate:
      ddl-auto: create-drop
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        format_sql: true

server:
  servlet:
    context-path: /
